require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - db/**
    - bin/**
  TargetRubyVersion: 3.0.3

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 100
  Exclude:
    - config/**/**

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - config/environments/**
