name: Continuous Integration

on: [pull_request, push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.0.3'

      - name: Install dependencies
        run: bundle install

      - name: Rubocop
        run: rubocop

      - name: Test
        run: rails t
