name: Continuous Integration

on: [pull_request, push]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/tests
    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: tests
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        options: >-
          --mount type=tmpfs,destination=/var/lib/postgresql/data
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.3'

      - name: Install dependencies
        run: bundle install

      - name: Rubocop
        run: rubocop

      - name: Test
        run: rails t
